name: Build & Deploy Angular Blade Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
               
      - name: Install dependencies
        run: npm install
        working-directory: /home/runner/work/xblade/xblade/src/xblade/xbladeshell
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
      - name: Build project
        run: npm run build
        working-directory: /home/runner/work/xblade/xblade/src/xblade/xbladeshell

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_OCEAN_0FA567F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/home/runner/work/xblade/xblade/src/xblade/xbladeshell'
          output_location: '/home/runner/work/xblade/xblade/src/xblade/xbladeshell/dist/xbladeshell'